# Aviumlabs-Cds.psm1
# Copyright 2024, 2025 Michael Konrad 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Tomcat Instance ID
$TcInstanceId = "-a"

# Lab Directories
$Directories = [ordered]@{
    "bin" = "bin\";
    "backups" = "apps\backups\";
    "downloads" = "apps\downloads\";
    "iiqkeys" = "apps\secrets\iiqkeys\";
    "secrets" = "apps\secrets\";
    "tomcat" = "apps\tomcat";
    "postgresdata" = "apps\postgresql\15\data"
}

# Lab secrets
$SecretFiles = [ordered]@{
    "ADSafeModeFile" = ".secret_iiqad_svc_pass";
    "KeyStoreFile" = ".secret_keystore";
    "TomcatSvcFile" = ".secret_tomcat_svc_pass";
    "TomcatManagerFile" = ".secret_tomcat_manager_pass";
    "TomcatRpaFile" = ".secret_tomcat_rpa_pass";
    "TomcatJmxFile" = ".secret_tomcat_jmx_pass";
    "PostgresFile" = ".secret_psql";
}

# Update these variables to preferred Apache Tomcat usernames 
# Leave *Pass blank, passwords will be generated by the script and copied to 
# the secrets directory.
$TomcatUsers = [ordered]@{
    "Manager" = "manager";
    "ManagerPass" = "";
    "RpaUser" = "rpa-tomcat";
    "RpaPass" = "";
    "JmxUser" = "jmx-tomcat";
    "JmxPass" = "";
}

New-Variable -Name Directories -Value $Directories -Scope Local -Force
New-Variable -Name SecretFiles -Value $SecretFiles -Scope Local -Force
New-Variable -Name TomcatUsers -Value $TomcatUsers -Scope Local -Force
New-Variable -Name TcInstanceId -Value $TcInstanceId -Scope Local -Force

Export-ModuleMember -Variable Directories, SecretFiles, TomcatUsers, TcId