# Packages.psm1
# Copyright 2024, 2025 Michael Konrad 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The Packages module creates the directory structure, installs and configures 
# the packages listed here. 
# Additionally the Packages module installs and configures the 
# Windows OpenSSH Capability and Windows Active Directory.

# Update these variables to preferred Active Directory settings 
# Leave TomcatPass blank, it will be generated by the script and copied to the 
# secrets directory .secret_tomcat_pass
$ADDomain = [ordered]@{
    "DomainName" = "aviumlabs.test";
    "NetbiosName" = "AVIUMLABS";
    "RootDN" = "DC=aviumlabs,DC=test";
    "ServerName" = "devsrv.aviumlabs.test";
    "Locality" = "Washington";
    "Organization" = "Aviumlabs";
    "Country" = "US";
    "WorkforceOU" = "Workforce";
    "ServiceOU" = "ServiceAccounts";
    "GroupOU" = "Groups";
    "LogonServiceGroup" = "LogonAsService";
    "TomcatUser" = "svc-tomcat";
    "TomcatPass" = "";
    "IiqAdUser" = "svc-iiqad";
    "Environment" = "Development";
}

# Update these variables to preferred Apache Tomcat usernames 
# Leave *Pass blank, passwords will be generated by the script and copied to 
# the secrets directory.
$TomcatUsers = [ordered]@{
    "Manager" = "manager";
    "ManagerPass" = "";
    "RpaUser" = "rpa-tomcat";
    "RpaPass" = "";
    "JmxUser" = "jmx-tomcat";
    "JmxPass" = "";
}

$Directories = [ordered]@{
    "bin" = "bin\";
    "backups" = "apps\backups\";
    "downloads" = "apps\downloads\";
    "iiqkeys" = "apps\secrets\iiqkeys\";
    "secrets" = "apps\secrets\";
    "tomcat" = "apps\tomcat";
}

$BasePackages = [ordered]@{
    "PowerShell-7.5.0-win-x64.msi" = @{ 
        endpoint = "https://github.com/PowerShell/PowerShell/releases/download/v7.5.0/PowerShell-7.5.0-win-x64.msi";
        halg = "SHA256";
        vhash = "6B988B7E236A8E1CF1166D3BE289D3A20AA344499153BDAADD2F9FEDFFC6EDA9";
        verified = $false;
    }
    "VSCodeSetup-x64-1.99.0.exe" = @{ 
        endpoint = "https://update.code.visualstudio.com/1.99.0/win32-x64/stable";
        halg = "SHA256"
        vhash = "c7263d720fd3624235d7846fbb1da587a822b1b79a75064e28358e6404b764f6";
        verified = $false;
    }
}

$Packages = [ordered]@{
    "ant-contrib-1.0b3-bin.zip" = @{
        endpoint = "$PSScriptRoot\Packages\ant-contrib-1.0b3-bin.zip";
        halg = "MD5";
        vhash = "c5a75fc28cbc52f09bd43b5506978601";
        verified = $false;
    }
    "apache-ant-1.10.15-bin.zip" = @{
        endpoint = "https://dlcdn.apache.org//ant/binaries/apache-ant-1.10.15-bin.zip";
        halg = "SHA512";
        vhash = "1de7facbc9874fa4e5a2f045d5c659f64e0b89318c1dbc8acc6aae4595c4ffaf90a7b1ffb57f958dd08d6e086d3fff07aa90e50c77342a0aa5c9b4c36bff03a9";
        verified = $false;
    }
    "apache-tomcat-9.0.102.exe" = @{
        endpoint = "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.102/bin/apache-tomcat-9.0.102.exe";
        halg = "SHA512";
        vhash = "8ddf5b5d41ec83b02a7bd74e9ccd36c99a56b6ba8a0f35e89d6bdc360c760ca7c56c64f93f7279d5ea9b1ec891c51e358f3d9de579571517bea4220c1778abc0";
        verified = $false;
    }
    "openjdk-21+35_windows-x64_bin.zip" = @{
        endpoint = "https://download.java.net/openjdk/jdk21/ri/openjdk-21+35_windows-x64_bin.zip";
        halg = "SHA256";
        vhash = "5434faaf029e66e7ce6e75770ca384de476750984a7d2881ef7686894c4b4944";
        verified = $false;
    }
    "postgresql-15.10-1-windows-x64.exe" = @{
        endpoint = "https://sbp.enterprisedb.com/getfile.jsp?fileid=1259343";
        halg = "SHA256";
        vhash = "CDCD0A767A7AD4AB0C4A5A59DC931D33F8899D172B6E209EBE1BB76796264FF9";
        verified = $false;
    }
    "postgresql-42.7.5.jar" = @{
        endpoint = "https://jdbc.postgresql.org/download/postgresql-42.7.5.jar";
        halg = "SHA256";
        vhash = "69020B3BD20984543E817393F2E6C01A890EF2E37A77DD11D6D8508181D079AB";
        verified = $false;
    }
    "tomcat-native-2.0.8-openssl-3.0.14-win32-bin.zip" = @{
        endpoint = "https://dlcdn.apache.org/tomcat/tomcat-connectors/native/2.0.8/binaries/tomcat-native-2.0.8-openssl-3.0.14-win32-bin.zip";
        halg = "SHA512";
        vhash = "a4a8816668f14a7461711e25cb9277534981936c9e6f8b00ae55084cb265dc1d89ad07fa508ae2e1f7832236dafafbdd9d76a313c87f34e00ecfdfe75776638a";
        verified = $false;
    }
}

New-Variable -Name ADDoamin -Value $ADDomain -Scope Script -Force
New-Variable -Name Directories -Value $Directories -Scope Script -Force
New-Variable -Name BasePackages -Value $BasePackages -Scope Script -Force
New-Variable -Name Packages -Value $Packages -Scope Script -Force


# =============================================================================
# Public API
# =============================================================================

<#
.SYNOPSIS 
    Install the prerequisite packages specified at the top of this file.
.DESCRIPTION
    Install the prerequisite packages specified at the top of this file; 
    requires administrative permission.
.PARAMETER Path
    If path is not provided, defaults to "C:\".
.EXAMPLE
    Install-BasePackages -Path "D:\"
#>
function Install-BasePackages {
    param (
        [string]$Path
    )
    Write-Host "Confirming this operating system is supported by this module."
    Assert-Environment

    if(-Not($Path)) {
        $Path = "C:\"
    } 

    Write-Host @"
    `nThese packages will be downloaded and installed on this system as well
    as the Windows OpenSSH capability and Active Directory.
"@
    foreach ($pkg in $BasePackages.Keys) {
        Write-Host "`n`t$($pkg)"
    }

    Write-Host "`n"
    # Process: 
    # Create Directories > Download Packages > 
    # Verify Packages > Install Packages > Configure Packages
    Add-Directories -Path $Path
    Get-Packages -Path $Path -Pkgs $BasePackages

    Install-PowerShell -Path $Path
    Install-VSCode -Path $Path
    Install-OpenSSH -Path $Path
    Initialize-OpenSSH -Path $Path
    Install-ActiveDirectory -Path $Path
}


<#
.SYNOPSIS 
    Install the prerequisite packages specified at the top of this file.
.DESCRIPTION
    Install the prerequisite packages specified at the top of this file; 
    requires administrative permission.
.PARAMETER Path
    If path is not provided, defaults to "C:\". drive letter is required by the 
    PostgreSQL installer.
.EXAMPLE
    Install-Packages -Path "C:\"
#>
function Install-Packages {
    param (
        [string]$Path
    )
    Write-Host "Confirming this operating system is supported by this module."
    Assert-Environment

    if(-Not($Path)) {
        $Path = "C:\"
    }

    Write-Host @"
    `nThis script will download, install and configure the packages required to 
    run SailPoint IdentityIQ 8.x on Windows 10 or higher.`n
    The following directories are created if they do not already exist: 
"@
    foreach ($dir in $Directories.Values) {
        Write-Host "`n`t$dir"
    }

    Write-Host @"
    `nThe following packages will be downloaded and installed on the system:
"@
    foreach ($pkg in $Packages.Keys) {
        Write-Host "`n`t$($pkg)"
    }
    Write-Host "`n"

    # Process: 
    # Create Directories > Download Packages > 
    # Verify Packages > Install Packages > Configure Packages
    Add-Directories -Path $Path
    Get-Packages -Path $Path -Pkgs $Packages

    # Install AD Management Tools and initialize baseline OUs
    Initialize-ADManagement
    # Initializes the system service accounts and security groups
    Initialize-ADServiceAccountsGroups -Path $Path
    # Applies the Development Server and updated Default Domain Group Policies
    Import-DevServerGPO -Path $Path
    # Applies the Logon As A Service Group Policy
    # Required for running Apache Tomcat under specified service account
    Import-LogonServiceGPO
    
    <##>
    Install-OpenJDK -Path $Path
    Install-PostgreSQL -Path $Path
    Install-ApacheAnt -Path $Path
    Install-ApacheTomcat -Path $Path
    Set-ApacheFSPermissions -Path $Path
    Initialize-ApacheTomcat -Path $Path
    Initialize-ApacheTomcatUsers -Path $Path
    Initialize-ApacheManagerHTML -Path $Path
    Set-PermanentEnvVariables -Path $Path
    
}


# =============================================================================
# Internal API
# =============================================================================
<#
.SYNOPSIS 
    Internal function to create the specific set of directories.
.DESCRIPTION
    Internal function to create the specific set of directories as 
    specified in this file.
.PARAMETER Path
    Root path.
.EXAMPLE
    Add-Directories -Path "C:\"
#>
function Add-Directories {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )

    Write-Host "Creating lab directories..."
    # Add the directory structure for this project
    Add-Directory -Path $Path -Name $Directories["bin"]
    Add-Directory -Path $Path -Name $Directories["backups"]
    Add-Directory -Path $Path -Name $Directories["downloads"]
    Add-Directory -Path $Path -Name $Directories["iiqkeys"]
    Add-Directory -Path $Path -Name $Directories["tomcat"]
    Write-Host "Lab directories setup completed."
}


<#
.SYNOPSIS 
    Internal function to create a directory at the specified path.
.DESCRIPTION
    Internal function to create a directory at the specified path, if the path 
    is not existing.
.PARAMETER Path
    The root path for the lab install.
.PARAMETER Name
    The name of the directory to create.
.EXAMPLE
    Add-Directory -Path "C:\" -Name "apps"
    Add-Directory -Path "C:\apps\tmp\" -Name "example"
#>
function Add-Directory {
    param (
        [Parameter(Mandatory)]
        [string]$Path,
        [Parameter(Mandatory)]
        [string]$Name
    )
    $item_path = $Path + $Name

    if (-Not(Test-Path -Path $item_path)) {
        Write-Host "Adding directory $item_path."
        New-Item -Path $Path -Name $Name -ItemType Directory | Out-Null
    } else {
        Write-Host "Skipping path $item_path already existing.`n"
    }
}


<#
.SYNOPSIS 
    Internal function to create CATALINA_BASE directories.
.DESCRIPTION
    Internal function to create instance specific CATALINA_BASE directories.
    This function is dependent on $env:CATALINA_BASE being defined.
.EXAMPLE
    Add-CatBaseDirectories
#>
function Add-CatBaseDirectories {
    $root = ($env:CATALINA_BASE).Split("\").Get(0)
    $root = $root + "\"
    $base_path = ($env:CATALINA_BASE).Split("C:\").Get(1)

    $tomcat_bin = "$base_path\bin"
    Add-Directory -Path $root -Name $tomcat_bin

    $tomcat_conf = "$base_path\conf"
    Add-Directory -Path $root -Name $tomcat_conf

    $tomcat_lib = "$base_path\lib"
    Add-Directory -Path $root -Name $tomcat_lib

    $tomcat_logs = "$base_path\logs"
    Add-Directory -Path $root -Name $tomcat_logs

    $tomcat_webapps = "$base_path\webapps"
    Add-Directory -Path $root -Name $tomcat_webapps

    $tomcat_work = "$base_path\work"
    Add-Directory -Path $root -Name $tomcat_work
}


<#
.SYNOPSIS 
    Internal function to add a member to a security group.
.DESCRIPTION
    Internal function to add a member to a security group. 
.EXAMPLE
    Add-MemberToSecurityGroup -Member $Member -SecurityGroup = $SecurityGroup
    Add-MemberToSecurityGroup -Member "CN=svc-tomcat,OU=ServiceAccounts,DC=aviumlabs,DC=test" -SecurityGroup "CN=LogonAsService,OU=Groups,DC=aviumlabs,DC=test"
#>
function Add-MemberToSecurityGroup {
    param (
        [Parameter(Mandatory)]
        [string]$Member,
        [Parameter(Mandatory)]
        [string]$SecurityGroup
    )
    Write-Host "Adding member $Member to $SecurityGroup..."
    Add-ADGroupMember -Identity $SecurityGroup -Members $Member | Out-Null

    if ($?) {
        Write-Host "Member $Member has been added to $SecurityGroup."
    } else {
        Write-Host "Failed to add member $Member to $SecurityGroup."
    }   
}


<#
.SYNOPSIS 
    Internal function to confirm Windows operating system and version.
.DESCRIPTION
    Internal function to confirm environment, terminates script if the 
    environment is not supported.
.EXAMPLE
    Assert-Environment
#>
function Assert-Environment {
    try {
        $os = (Get-CimInstance -ClassName CIM_OperatingSystem).Caption
        if ( $os -match "Windows") {
            $os_version = [Environment]::OSVersion.Version.Major
            if ( $os_version -ge 10 ) {
                return $true
            } else {
                Throw "Operating system version not supported."
            }
        }
    } catch {
        $exception_name = $Error[0].Exception.GetType().FullName
        Write-Host "Exception name...$exception_name"
        Write-Error $Error[0]
    }
}


<#
.SYNOPSIS 
    Verifies the integrity a file based on its secure hash checksum.
.DESCRIPTION
    Verifies the integrity a file based on its secure hash checksum.
.PARAMETER PkgPath
    The full path of the package to be verified. 
.PARAMETER Hash
    The verification hash.
.PARAMETER Algorithm
    The secure hash algorithm to use for verification.
.EXAMPLE
    Assert-Integrity -PkgPath "C:\test.zip" -Hash "ab3ed4..." -Alg "SHA256"
#>
function Assert-Integrity {
    param (
        [Parameter(Mandatory)]
        [string]$PkgPath,
        [Parameter(Mandatory)]
        [string]$Hash,
        [Parameter(Mandatory)]
        [string]$Alg
    )
    $dl_hash = Get-FileHash -Path $PkgPath -Algorithm $Alg

    return $dl_hash.Hash -eq $Hash
}


<#
.SYNOPSIS 
    Internal function to backup a group policy.
.DESCRIPTION
    Internal function to backup a group policy.
.PARAMETER Path
    The root path of the lab installation.
.PARAMETER GpoName
    The name of the group policy to backup.
.EXAMPLE
    Backup-GroupPolicy -Path "C:\" -GpoName "Default Domain Policy"
#>
function Backup-GroupPolicy {
    param (
        [Parameter(Mandatory)]
        [string]$Path,
        [Parameter(Mandatory)]
        [string]$GpoName
    )
    # Export the GPO, documentation only
    $bk_path = $Path + $Directories["backups"]
    Backup-Gpo -Name $GpoName -Path $bk_path -Comment $GpoName
}


<#
.SYNOPSIS 
    Internal function to get closest multiple for the power 2.
.DESCRIPTION
    Internal function to get closest multiple for the power 2, to set
    JVM memory requirements.
.PARAMETER Num
    The current total amount of Random Access Memory
.EXAMPLE
    Get-ClosestMultiple -Num $total_ram
#>
function Get-ClosestMultiple {
    param (
        [Parameter(Mandatory)]
        [int]$Num
    )
    $Num = $Num + 1
    $Num = $Num - ($Num % 2)

    return $Num
}


<#
.SYNOPSIS 
    Internal function to retrieve the package filename.
.DESCRIPTION
    Internal function to retrieve the package filename from Packages dictionary,
    package dictionaries are defined at the top of this script.
.PARAMETER Name
    Name of the package to lookup.
.PARAMETER Pkgs
    The packages dictionary contiaining the package to be looked up.
.EXAMPLE
    Get-PackageName -Name "PowerShell" -Pkgs $BasePackages
    Get-PackageName -Name "OpenJDK" -Pkgs $Packages
#>
function Get-PackageName {
    param (
        [Parameter(Mandatory)]
        [string]$Name,
        [Parameter(Mandatory)]
        [System.Collections.Hashtable]$Pkgs
    )
    foreach ($pkg in $Pkgs.Keys) {
        if ( $($pkg) -Match $Name ) {
            $filename = $($pkg)
        }
    }

    return $filename
}


<#
.SYNOPSIS 
    Internal function to download a specific set of packages.
.DESCRIPTION
    Download the packages passed in the Pkgs dictionary; package dictionaries 
    are defined at the top of this script.
.PARAMETER Path
    Root path of the lab installation.
.PARAMETER Pkgs
    The packages dictionary to be download.
.EXAMPLE
    Get-Packages -Path "C:\" -Pkgs $BasePackages
    Get-Packages -Path "C:\" -Pkgs $Packages
#>
function Get-Packages {
    param (
        [Parameter(Mandatory)]
        [string]$Path,
        [Parameter(Mandatory)]
        [System.Collections.Hashtable]$Pkgs
    )
    $dl_path = $Path + $Directories["downloads"]
    Set-Location -Path $dl_path

    # Packages are defined at the top of the module
    foreach ($pkg in $Pkgs.Keys) {
        $download = @{
            FileName = $($pkg)
            Uri = $($Pkgs[$pkg]['endpoint'])
        }
        # check if package is already existing, if not download
        $pkg_path = $dl_path + $pkg
        if (-Not (Test-Path -Path $pkg_path)) {
            if ($pkg -eq "ant-contrib-1.0b3-bin.zip") {
                $ant_contrib_path = $Packages[$pkg]['endpoint']
                Copy-Item -Path $ant_contrib_path -Destination $dl_path
                $pkg_path = $dl_path + $pkg
                $res = $true
            } else {
                $res = Invoke-Download @download
            }
            if ($res) {
                Write-Host "$pkg download completed."
                Write-Host "Verifying $pkg integrity..." 
                $pkg_sha = $Pkgs[$pkg]['vhash']
                $ast = Assert-Integrity -PkgPath $pkg_path -Hash $pkg_sha -Alg $Pkgs[$pkg]['halg']

                if ($ast) {
                    # Update verified dictionary
                    $Pkgs[$pkg]['verified'] = $true
                    Write-Host "$pkg integrity verified."
                } else {
                    Write-Host "$pkg intgretiy verification failed."
                }
            } else {
                Write-Host "$pkg download failed."
            }
        } else {
            Write-Host "Skipping $pkg already existing."
        }  
    }

    Set-Location -Path $Path
}
    

<#
.SYNOPSIS 
    Internal function to import Development Server group policy.
.DESCRIPTION
    Internal function to import Development Server group policy. 
    Removes the requirement to press CTRL-ALT-DEL to login and lock 
    screen timeout - NOT suitable for production.
    This function is also overloaded to update the migration table.
.PARAMETER Path
    Root path of the lab installation.
.EXAMPLE
    Import-DevServerGPO -Path "C:\"
#>
function Import-DevServerGPO {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    $domain = [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().Name
    if ($domain) {
        # Update migration table with current domain
        $mig_table_path = "$PSScriptRoot\GPO\testdomain.migtable"
        $update_mig_path = "$PSScriptRoot\GPO\newdomain.migtable"
        $match_term = "testdomain.test"
        ((Get-Content -Path $mig_table_path -Raw) -Replace $match_term, $domain) `
        | Set-Content -Path $update_mig_path

        Write-Host "Importing Development Server group policy..."
        # Import Development Server GPO
        $gpo_path = "$PSScriptRoot\GPO\DevelopmentServer"
        $policy_name = "Development Server Policy"
        Import-GPO -BackupGpoName $policy_name -TargetName $policy_name `
        -Path $gpo_path -Domain $domain -MigrationTable $update_mig_path `
        -CreateIfNeeded | Out-Null

        # Confirm the command executed successfully
        if ($?) {
            Write-Host "Succesfully imported Development Server group policy."
            Write-Host "Linking Development Server group policy to domain..."
            # Link the GPO to the top level domain; for ease of use as a development 
            # environment
            $domain_dn = $ADDomain["RootDN"]
            Get-GPO $policy_name | New-GPLink -Target $domain_dn -LinkEnabled Yes | Out-Null

            if ($?) {
                Write-Host "Development Server group policy has been linked to the domain."
            } else {
                Write-Host "Failed to link the Development Server group policy."
            }
        } else {
            Write-Host "Failed to import Development Server group policy."
        }
    } else {
        Write-Host "Failed to import group policy, unable to get AD domain."
    }
    
}


<#
.SYNOPSIS 
    Internal function to import logon as a service group policy.
.DESCRIPTION
    Internal function to import logon as a service group policy. Dependent 
    on the security group LogonAsService existing in the domain. This security 
    group and the Apache Tomcat service account are automatically created 
    prior to running this function. 
.EXAMPLE
    Import-LogonServiceGPO
#>
function Import-LogonServiceGPO {
    $domain = [System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain().Name
    if ($domain) {
        Write-Host "Importing Logon As A Service group policy..."
        # Import GPO
        $gpo_path = "$PSScriptRoot\GPO\LogonAsService"
        $policy_name = "Logon As A Service Policy"
        $mig_table_path = "$PSScriptRoot\GPO\newdomain.migtable"

        Import-GPO -BackupGpoName $policy_name -TargetName $policy_name `
        -Path $gpo_path -Domain $domain -MigrationTable $mig_table_path `
        -CreateIfNeeded | Out-Null
        
        if ($?) {
            Write-Host "Succesfully imported Logon As A Service group policy."
            Write-Host "Linking Logon As A Service group policy to domain..."
            # Link the GPO to the top level domain; for ease of use as a development 
            # environment
            $domain_dn = $ADDomain["RootDN"]
            Get-GPO $policy_name | New-GPLink -Target $domain_dn -LinkEnabled Yes | Out-Null

            if ($?) {
                Write-Host "Logon As A Service group policy has been linked to the domain."
            } else {
                Write-Host "Failed to link the Logon As A Service group policy."
            }
        } else {
            Write-Host "Failed to import Logon As A Service group policy."
        }
    } else {
        Write-Host "Failed to import Logon As A Service, unable to get AD domain."
    }
}


<#
.SYNOPSIS 
    Internal function to initialize Active Directory Management Tools.
.DESCRIPTION
    Internal function to initialize Active Directory Management Tools. Creates 
    the Organizational Units defined in the ADDomain dictionary at the top of 
    this script.
.PARAMETER Path
    Root path the download directory.
.PARAMETER Pkgs
    The packages dictionary to be download.
.EXAMPLE
    Initialize-ADManagement
#>
function Initialize-ADManagement {
    Write-Host "Installing Active Directory Management Tools..."
    # Get-WindowsFeature | ? Name -like 'RSAT*'
    Install-WindowsFeature RSAT-ADDS-Tools | Out-Null
    if ($?) {
        Write-Host "Active Directory Management Tools installed."
    } else {
        Write-Host "Failed to install Active Directory Management Tools."
    }
    
    # Setup AD Structure
    Import-Module ActiveDirectory

    # Setup Workforce OU
    $workforce_ou = $ADDomain["WorkforceOU"] 
    New-ADOrganizationalUnit $workforce_ou -Path $ADDomain["RootDN"]

    # Setup Service Accounts OU
    $svc_ou = $ADDomain["ServiceOU"]
    New-ADOrganizationalUnit $svc_ou -Path $ADDomain["RootDN"]

    # Setup Groups OU
    $grp_ou = $ADDomain["GroupOU"]
    New-ADOrganizationalUnit $grp_ou -Path $ADDomain["RootDN"]
}


<#
.SYNOPSIS 
    Internal function to initialize AD service accounts and security groups.
.DESCRIPTION
    Internal function to initialize AD service accounts and security groups. Creates 
    the service accounts and security groups defined in the ADDomain dictionary at the 
    top of this script. Saves the randomly generated passwords to the `secrets`
    directory.
.PARAMETER Path
    Root path of the lab install.
.EXAMPLE
    Initialize-ADServiceAccountsGroups -Path $Path
    Initialize-ADServiceAccountsGroups -Path "C:\"
#>
function Initialize-ADServiceAccountsGroups {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    Write-Host "Initializing system service accounts in AD..."
    $svc_pass = New-RandomPassword
    $svc_pass += '-+'
    $svc_filename = ".secret_iiqad_svc_pass"
    Save-RandomPassword -Path $Path -Name $svc_filename -Secret $svc_pass
    
    # Create the svc-iiqad service account
    $AccountName = $ADDomain["IiqAdUser"]
    $AccountPassword = ConvertTo-SecureString "$svc_pass" -AsPlainText -Force
    $Description = "IdentityIQ AD service account"
    New-ADServiceAccount -AccountName $AccountName -AccountPassword $AccountPassword -Description $Description

    # Add IIQ AD service account to Account Operators security group
    $Member = Get-ADUser $ADDomain["IiqAdUser"]
    $SecurityGroup = "CN=Account Operators,CN=Builtin," + $ADDomain["RootDN"]
    Add-MemberToSecurityGroup -Member $Member -SecurityGroup $SecurityGroup

    $svc_pass = New-RandomPassword
    $svc_pass += '-+'
    $svc_filename = ".secret_tomcat_svc_pass"
    Save-RandomPassword -Path $Path -Name $svc_filename -Secret $svc_pass
    # Save password to dictionary for Apache Tomcat initialization
    $ADDomain["TomcatPass"] = $svc_pass

    # Create the svc-tomcat service account
    $AccountName = $ADDomain["TomcatUser"]
    $AccountPassword = ConvertTo-SecureString "$svc_pass" -AsPlainText -Force
    $Description = "Apache Tomcat service account"
    New-ADServiceAccount -AccountName $AccountName -AccountPassword $AccountPassword -Description $Description

    # Create the LogonAsService security group
    $GroupName = $ADDomain["LogonServiceGroup"]
    $Description = "Logon As a Service security group."
    New-ADSecurityGroup -GroupName $GroupName -Description $Description | Out-Null

    # Add Apache Tomcat service account to Logon As a Service security group
    $Member = Get-ADUser $ADDomain["TomcatUser"]
    $SecurityGroup = Get-ADGroup $ADDomain["LogonServiceGroup"]
    Add-MemberToSecurityGroup -Member $Member -SecurityGroup $SecurityGroup

    Write-Host "Initialization of AD service accounts is completed."
}


<#
.SYNOPSIS 
    Internal function to configure an Apache Tomcat instance.
.DESCRIPTION
    Configures an Apache Tomact instance base on the configuration in this 
    script.
.PARAMETER Path
    Root path of the lab installation.
.PARAMETER InstanceId
    The name of the instance to configure, defaults to <hostname>-a.
.EXAMPLE
    Initialize-ApacheTomcat -Path "C:\" 
    Initialize-ApacheTomcat -Path "C:\" -InstanceId "devsrv-b"
#>
function Initialize-ApacheTomcat {
    param (
        [Parameter(Mandatory)]
        [string]$Path,
        [string]$InstanceId
    )
    if (-Not $InstanceId) {
        $server_name = hostname
    } else {
        $server_name = $InstanceId
    }
    Write-Host "Configuring Apache Tomcat..."
    Add-CatBaseDirectories
    # Harden Tomcat
    # Backup and remove the following directories from tomcat\webapps 
    #   * docs
    #   * ROOT
    Write-Host "Backing up Apache Tomcat webapps..."
    $src_path = "$env:CATALINA_HOME\webapps"
    $date = Get-Date -Format "yyyyddMMHHmm"
    $bk_path = $Path + $Directories["backups"] + "$date-webapps.zip"

    Compress-Archive -Path $src_path -DestinationPath $bk_path | Out-Null
    Remove-Item "$src_path\docs" -Recurse -Force
    Remove-Item "$src_path\ROOT" -Recurse -Force
    Write-Host "Apache Tomcat webapss backup completed."

    # Configure CATALINA_BASE
    Write-Host "Configure CATALINA_BASE..."
    Copy-Item -Path "$env:CATALINA_HOME\bin\tomcat-juli.jar" -Destination "$env:CATALINA_BASE\bin"
    Copy-Item -Path "$env:CATALINA_HOME\conf\server.xml" -Destination "$env:CATALINA_BASE\conf"
    Copy-Item -Path "$env:CATALINA_HOME\conf\web.xml" -Destination "$env:CATALINA_BASE\conf"
    Copy-Item -Path "$env:CATALINA_HOME\conf\tomcat-users.xml" -Destination "$env:CATALINA_BASE\conf"
    Copy-Item -Path "$env:CATALINA_HOME\conf\logging.properties" -Destination "$env:CATALINA_BASE\conf"
    Write-Host "CATALINA_BASE configuration completed."

    # Tomcat TLS Certificate
    Write-Host "Generating Tomcat keystore..."
    $key_alias = $ADDomain["ServerName"]
    $locality = $ADDomain["Locality"]
    $org = $ADDomain["Organization"]
    $country = $ADDomain["Country"]
    $dname = "CN=$key_alias,L=$locality,O=$org,C=$country"
    $keystore_path = "$env:CATALINA_BASE\conf\tomcat.jks"
    $keystore_pass = New-RandomPassword
    $keystore_filename = ".secret_keystore"
    Save-RandomPassword -Path $Path -Name $keystore_filename -Secret $keystore_pass

    # Generate the keystore and private/public key pair for TLS communication
    keytool -genkeypair -keyalg EC -groupname secp384r1 -alias $key_alias -dname $dname `
    -validity 180 -keystore $keystore_path -storepass $keystore_pass
    Write-Host "Tomcat keystore $keystore_path generated."

    Write-Host "Opening inbound Apache Tomcat TLS port 8443..."
    # Open the Apache Tomcat inbound TLS port 8443
    New-NetFirewallRule -Name "Tomcat TLS" -Enabled True `
    -DisplayName "Tomcat TLS port 8443 inbound allow" -Direction Inbound `
    -Protocol TCP -LocalPort 8443 -RemoteAddress LocalSubnet -Action Allow `
    -Description "Tomcat Transport Layer Security Allow on Port 8443" | Out-Null
    Write-Host "Apache Tomcat port 8443 opened."

    Write-Host "Backing up Apache Tomcat CATALINA_BASE\conf..."
    $src_path = "$env:CATALINA_BASE\conf\*"
    $date = Get-Date -Format "yyyyddMMHHmm"
    $bk_path = $Path + $Directories["backups"] + "$date-cat-base-conf.zip"

    Compress-Archive -Path $src_path -DestinationPath $bk_path | Out-Null
    Write-Host "Apache Tomcat CATALINA_BASE\conf backup completed."

    Write-Host "Configuring Apache Tomcat TLS listener..."
    $server_xml_path = "$env:CATALINA_BASE\conf\server.xml"
    $line_to_match = '<Service name="Catalina">'
    $connector = "$line_to_match`n`n  <Connector port=""8443"" maxThreads=""200"" scheme=""https""
    `tsecure=""true"" SSLEnabled=""true""
    `tkeystoreFile=""$keystore_path""
    `tkeystorePass=""$keystore_pass""
    `tkeyAlias=""$key_alias""
    `tsslEnabledProtocols=""TLSv1.2+TLSv1.3""
    `tclientAuth=""false"" sslProtocol=""TLS""
    `tURIEncoding=""UTF-8"" />`n"

    # Update server.xml
    ((Get-Content -path $server_xml_path -Raw) -Replace $line_to_match, $connector) `
    | Set-Content -Path $server_xml_path
    Write-Host "Apache Tomcat TLS listener configured."

    Write-Host "Configuring Apache Tomcat default encoding - UTF-8..."
    # Update Default Encoding to UTF-8
    $match_term = '<Connector port="8080" (.*\s+){4}'
    $append_term = '$&URIEncoding="UTF-8"'

    # Update server.xml
    ((Get-Content -Path $server_xml_path -Raw) -Replace $match_term, $append_term) `
    | Set-Content -Path $server_xml_path
    Write-Host "Apache Tomcat UTF-8 encoding configured."

    Write-Host "Configuring Apache Tomcat Engine settings..."
    $server_name = $server_name.ToLower()
    # Update defaultHost to hostname
    
    $match_term = '(<Engine name="Catalina" defaultHost=")localhost">'
    ((Get-Content -Path $server_xml_path -Raw) -Replace $match_term, `
    ('$1' + $server_name + '"' + " jvmRoute=""$server_name"">")) `
    | Set-Content -Path $server_xml_path

    # Update Host to hostname
    $match_term = '(Host name=")localhost"'
    ((Get-Content -Path $server_xml_path -Raw) -Replace $match_term, ('$1' + $server_name + '"')) `
    | Set-Content -Path $server_xml_path

    $match_term = '(prefix=")localhost_access_log'
    ((Get-Content -Path $server_xml_path -Raw) -Replace $match_term, ('$1' + "$server_name-access-log")) `
    | Set-Content -Path $server_xml_path
    Write-Host "Apache Tomcat Engine settings completed."

    Write-Host "Configuring Apache Tomcat logging.properites..."
    $logging_prop_path = "$env:CATALINA_BASE\conf\logging.properties"

    $match_term = 'localhost'
    ((Get-Content -Path $logging_prop_path -Raw) -Replace $match_term, $server_name) `
    | Set-Content -Path $logging_prop_path

    $match_term = '(1catalina.org.apache.juli.AsyncFileHandler.prefix = )catalina.'
    ((Get-Content -Path $logging_prop_path -Raw) -Replace $match_term, ('$1' + $server_name +'-catalina.')) `
    | Set-Content -Path $logging_prop_path

    $match_term = '(3manager.org.apache.juli.AsyncFileHandler.prefix = )manager.'
    ((Get-Content -Path $logging_prop_path -Raw) -Replace $match_term, ('$1' + $server_name +'-manager.')) `
    | Set-Content -Path $logging_prop_path

    $match_term = '(4host-manager.org.apache.juli.AsyncFileHandler.prefix = )host-manager.'
    ((Get-Content -Path $logging_prop_path -Raw) -Replace $match_term, ('$1' + $server_name +'-host-manager.')) `
    | Set-Content -Path $logging_prop_path
    Write-Host "Apache Tomcat logging.properties configuration completed."

    Write-Host "Configuring Apache Tomcat ROOT redirect..."
    # Create ROOT Context redirect
    $context_xml_path = "$env:CATALINA_BASE\conf\context.xml"
    $context_xml = "<Context path=""/"" docBase=""${catalina.base}/webapps/identityiq""/>"
    Set-Content -Path $context_xml_path -Value $context_xml
    Write-Host "Apache Tomcat ROOT redirect configured."

    # Install Tomcat Service
    Write-Host "Installing Apache Tomcat Windows service..."
    $svc_installer = "$env:CATALINA_HOME\bin\service.bat"
    .$svc_installer install IdentityIQ | Out-Null
    Write-Host "Apache Tomcat Windows service installed."

    # Get the amount of physical memory
    $ram_info = (systeminfo | Select-String 'Total Physical Memory:').ToString().Split(':')[1].Trim()
    $total_ram, $sz_label = $ram_info.Split()
    $total_ram = [int]$total_ram
    if (($sz_label -eq 'MB') -or ($sz_label -eq 'GB')) {
        if ($total_ram -gt 8000) {
            $jvm_max = Get-ClosestMultiple -Num ($total_ram * 0.6022)
            $jvm_min = Get-ClosestMultiple -Num ($total_ram * 0.1020)
        } 
    } else {
        $jvm_max = 512
        $jvm_min = 256
    }

    # Create temp softlink to the logs directory, 
    $temp_path = "$env:CATALINA_BASE\temp"
    $logs_path = "$env:CATALINA_BASE\logs"
    cmd /c mklink /D $temp_path $logs_path

    $service_user = $ADDomain["NetbiosName"] + "\" + $ADDomain["TomcatUser"]
    $std_out_filename = $server_name + "-identityiq-stdout.YEAR-MONTH-DAY.log"
    $std_err_filename = $server_name+ "-identityiq-stderr.YEAR-MONTH-DAY.log"

    Write-Host "Updating Apache Tomcat Windows service..."
    # Update Tomcat Service
    tomcat9 //US//IdentityIQ --Description "Apache Tomcat IdentityIQ Server" `
    --JvmMs $jvm_min --JvmMx $jvm_max ++JvmOptions9 --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED `
    --LogPrefix "$server_name-common-daemons" `
    --ServiceUser $service_user `
    --ServicePassword $ADDomain["TomcatPass"] `
    --StdOutput $std_out_filename `
    --StdError $std_err_filename | Out-Null
    Write-Host "Apache Tomcat Windows service update completed."

    # Start Tomcat Service to create Engine directory
    tomcat9 //ES//IdentityIQ | Out-Null
    if ($?) {
        Write-Host "Apache Tomcat instance started."
    }
    tomcat9 //SS/IdentityIQ | Out-Null
    if ($?) {
        Write-Host "Apache Tomcat instance stopped."
    }

    # Test Tomcat configuration
    Write-Host "Testing Apache Tomcat configuration..."
    $config_log = $Path + $Directories["backups"] + "$date-tomcat-configtest.log"
    Write-Host "Configtest log saved to $config_log"
    $tester = "$env:CATALINA_HOME\bin\configtest.bat" 
    .$tester > $config_log 2>&1
    Write-Host "Apache Tomcat config test report generated."

    Write-Host "Adding Apache Tomcat manager application..."
    $mgr_base_path = "$env:CATALINA_BASE\conf\Catalina\"
    Add-Directory -Path $mgr_base_path -Name $server_name

    $manager_xml_path = $mgr_base_path + "$server_name\manager.xml"
    $manager_xml_content = @"
    <Context privileged="true" antiResourceLocking="false"
             docBase="`${catalina.home}/webapps/manager">
      <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"
                       sameSiteCookies="strict" />
      <Valve className="org.apache.catalina.valves.RemoteAddrValve"
             allow="127\.\d+\.\d+\.\d+|192\.\d+\.\d+\.\d+" />
      <Manager sessionAttributeValueClassNameFilter="java\.lang\.(?:Boolean|Integer|Long|Number|String)|org\.apache\.catalina\.filters\.CsrfPreventionFilter\$LruCache(?:\$1)?|java\.util\.(?:Linked)?HashMap"/>
    </Context>
"@
    Set-Content -Path $manager_xml_path -Value $manager_xml_content
    Write-Host "Apache Tomcat manager application added."

    Write-Host "Logging Tomcat version..."
    $log_version = $Path + $Directories["backups"] + "$date-tomcat-version.log"
    version.bat | Out-File $log_version
    Write-Host "Tomcat version logged to $log_version."

    Write-Host "Setting IdentityIQ Tomcat to start automatically..."
    Set-Service -Name "IdentityIQ" -StartupType Automatic | Out-Null
    Write-Host "IdentityIQ Tomcat service set to start automatically."
}


<#
.SYNOPSIS 
    Internal function to customize Apache Tomcat manager GUI.
.DESCRIPTION
    Internal function to customize Apache Tomcat manager GUI, to show company 
    and environment, i.e., Development, Staging, Production as set in the 
    ADDomain["Enviornment"] setting. 
.PARAMETER Path
    Root path of the lab installation.
.EXAMPLE
    Initialize-ApacheManagerHTML -Path "C:\" 
#>
function Initialize-ApacheManagerHTML {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    # Backup originial web.xml file
    Write-Host "Backing up Apache Tomcat manager web.xml..."
    $manager_web_xml_path = "$env:CATALINA_HOME\webapps\manager\WEB-INF\web.xml"
    $date = Get-Date -Format "yyyyddMMHHmm"
    $bk_path = $Path + $Directories["backups"] + "manager-web-xml.zip"

    Compress-Archive -Path $manager_web_xml_path -DestinationPath $bk_path | Out-Null
    Write-Host "Apache Tomcat manager web.xml backup completed."

    # Set a sub title for Tomcat Manager application
    # Parameter is set in the $env:CATALINA_HOME\webapps\manager\WEB-INF\web.xml
    #<!-- Uncomment this to set a sub-title for the manager web application main
    #     page. It must be XML escaped, valid HTML.
    #<init-param>
    #  <param-name>htmlSubTitle</param-name>
    #  <param-value>Sub-Title</param-value>
    #</init-param>
    #-->
    $company_name = $ADDomain["Organization"]
    $iiq_env = $ADDomain["Environment"]
    $subtitle = "$company_name &lt;br&gt;&lt;i style=&apos;color:GoldenRod&apos;&gt;$iiq_env&lt;/i&gt;"

    # Set the manager application sub-title value
    $match_term = '([\s]*<param-value>)Sub-Title(</param-value>)'
    ((Get-Content -Path $manager_web_xml_path -Raw) -Replace $match_term, `
    ('$1' + $subtitle + '$2')) | Set-Content -Path $manager_web_xml_path

    # Remove xml comment tags
    $match_content = "(<!-- Uncomment this to set a sub-title[\s\S]*?)(<init-param>[\s\S\n]*?<param-name>htmlSubTitle</param-name>[\s\S\n.,]*?)-->"
    ((Get-Content -Path $manager_web_xml_path -Raw) -Replace $match_content, ('$1' + "-->`n" + '    $2')) `
    | Set-Content -Path $manager_web_xml_path
}


<#
.SYNOPSIS 
    Internal function to initialize Apache Tomcat OOTB users.
.DESCRIPTION
    Internal function to configure Apache Tomcat users for controlling 
    access to the Manager application. Passwords are generated anad stored in 
    the secrets directory.
.PARAMETER Path
    Root path of the lab installation.
.EXAMPLE
    Initialize-ApacheTomcatUsers -Path "C:\" 
#>
function Initialize-ApacheTomcatUsers {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
     # Backup originial web.xml file
     Write-Host "Backing up Apache Tomcat tomcat-users.xml..."
     $tomcat_users_xml_path = "$env:CATALINA_BASE\conf\tomcat-users.xml"
     $date = Get-Date -Format "yyyyddMMHHmm"
     $bk_path = $Path + $Directories["backups"] + "tomcat-users-xml.zip"
 
     Compress-Archive -Path $tomcat_users_xml_path -DestinationPath $bk_path | Out-Null
     Write-Host "Apache Tomcat tomcat-users.xml backup completed."
    # The OOTB Tomcat users are defined in conf/tomcat-users.xml
    # Usernames are defined at the top of this script in the TomcatUsers 
    # dictionary.
    #<!--
      #<user username="admin" password="<must-be-changed>" roles="manager-gui"/>
      #<user username="robot" password="<must-be-changed>" roles="manager-script"/>
    #-->

    $manager_id = $TomcatUsers["Manager"]
    $rpa_id = $TomcatUsers["RpaUser"]
    $jmx_id = $TomcatUsers["JmxUser"]

    $manager_pass = New-RandomPassword
    $mgr_pass_filename = ".secret_tomcat_manager_pass"
    Save-RandomPassword -Path $Path -Name $mgr_pass_filename -Secret $manager_pass

    $rpa_pass = New-RandomPassword
    $rpa_pass_filename = ".secret_tomcat_rpa_pass"
    Save-RandomPassword -Path $Path -Name $rpa_pass_filename -Secret $rpa_pass

    $jmx_pass = New-RandomPassword
    $jmx_pass_filename = ".secret_tomcat_jmx_pass"
    Save-RandomPassword -Path $Path -Name $jmx_pass_filename -Secret $jmx_pass

    # Append the JMX user credentials and role to the standard users
    $match_robot = '<user username="robot".*/>'
    $append_term = "$&`n  <user username=""$jmx_id"" password=""$jmx_pass"" roles=""manager-jmx""/>"
    ((Get-Content -Path $tomcat_users_xml_path -Raw) -Replace $match_robot, $append_term) `
    | Set-Content -Path $tomcat_users_xml_path

    # Initialize the manager-gui role
    $match_admin = '(<user username=")admin" (password=")<must-be-changed>" (roles="manager-gui"/>)'
    ((Get-Content -Path $tomcat_users_xml_path -Raw) -Replace $match_admin, `
    ('$1' + $manager_id + '"' + ' $2' + "$manager_pass" + '"' + ' $3')) `
    | Set-Content -Path $tomcat_users_xml_path

    # Initialize the manager-script role
    $match_robot = '(<user username=")robot" (password=")<must-be-changed>" (roles="manager-script"/>)'
    ((Get-Content -Path $tomcat_users_xml_path -Raw) -Replace $match_robot, `
    ('$1' + $rpa_id + '"' + ' $2' + "$rpa_pass" + '"' + ' $3')) `
    | Set-Content -Path $tomcat_users_xml_path
    
    # Remove xml comment tags
    $match_content = "<!--([\n\s]*?<user username=""$manager_id""[\s\S\n]*?)-->"
    ((Get-Content -Path $tomcat_users_xml_path -Raw) -Replace $match_content, '$1') `
    | Set-Content -Path $tomcat_users_xml_path
} 


<#
.SYNOPSIS 
    Internal function to add the Windows OpenSSH capability. 
.DESCRIPTION
    Internal function to add and configure the Windows OpenSSH capability. 
    Sets the default remote shell to PowerShell 7.5.0.
.PARAMETER Path
    If path is not provided, defaults to "C:\".
.EXAMPLE
    Initialize-OpenSSH -Path "D:\"
#>
function Initialize-OpenSSH {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    Write-Host "Configuring OpenSSH..."
    # Configure OpenSSH 
    $filename = "sshd_config"
    $config_path = "$env:ProgramData\ssh\$filename"

    if (-Not(Test-Path -Path $config_path)) {
        # Backup config file
        $bk_path = $Path + $Directories["backups"]
        $date = Get-Date -Format "yyyyddMM"
        Compress-Archive -Path $config_path -DestinationPath ($bk_path + "$date-$filename.zip")

        # Update PubkeyAuthentication
        $match_line = '#(PubkeyAuthentication yes)'
        ((Get-Content -Path $config_path -Raw) -Replace $match_line, '$1') | Set-Content -Path $config_path

        # Update PasswordAuthentication
        $match_line = '#(PasswordAuthentication yes)'
        ((Get-Content -Path $config_path -Raw) -Replace $match_line, '$1') | Set-Content -Path $config_path

        # Set PowerShell 7 as Default SSH Shell
        $line_to_match = "Subsystem`tsftp`tsftp-server.exe"
        $pwshell = "$line_to_match`nSubsystem`tpowershell`tc:/progra~1/powershell/7/pwsh.exe`t-sshs`t-NoLogo"
        ((Get-Content -Path $config_path -Raw) -replace $line_to_match, $pwshell) | Set-Content -Path $config_path

        # Confirm firewall rules 
        if (!(Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue | Select-Object Name, Enabled)) {
            Write-Output "Firewall Rule 'OpenSSH-Server-In-TCP' does not exist, creating it..."
            New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
            -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
        } else {
            Write-Output "Firewall rule 'OpenSSH-Server-In-TCP' is existing."
        }

        # Set Default OpenSSH Shell 
        New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell `
        -Value "C:\Progra~1\PowerShell\7\pwsh.exe" -PropertyType String -Force

        Write-Host "OpenSSH configured."
    } else {
        Write-Host "OpenSSH already configured, not modifying."
    }
}


<#
.SYNOPSIS 
    Internal function to install and configure Active Directory.
.DESCRIPTION
    Install and configure Active Directory based on the parameters defined 
    at the top of this script or the parameters passed in. A random password
    is generated for the `Safe Mode Administrator Password` and save to the 
    .\.secret_ad_safe_mode in the secrets directory.
.PARAMETER Path
    The root installation path, defaults to "C:\"
.PARAMETER ServerName
    Name of the server to install Active Directory Domain Services.
.PARAMETER DomainName
    Name of the Active Directory Domain.
.PARAMETER NetbiosName
    NetBios Name of the Active Directory Domain.
.EXAMPLE
    Install-ActiveDirectory -Path "D:\" -DomainName "aviumlabs.test" 
        -NetbiosName "AVIUMLABS"
    Install-ActiveDirectory -Path "D:\"
#>
function Install-ActiveDirectory {
    param (
        [Parameter(Mandatory)]
        [string]$Path,
        [string]$DomainName,
        [string]$NetbiosName
    )
    Write-Host "Installing Active Directory Domain Services..."

    # Install Active Directory
    Install-WindowsFeature AD-Domain-Services

    if (-Not $DomainName) {
        $DomainName = $ADDomain["DomainName"] 
    }

    if (-Not $NetbiosName) {
        $NetbiosName = $ADDomain["NetbiosName"]
    }

    Write-Host "Active Domain Services installed."
    Write-Host "Configuring the Active Directory domain $DomainName."
    # Configure Active Directory
    Import-Module ADDSDeployment

    $pwd = New-RandomPassword
    # Active Directory password policy requires uppercase, lowercase, numbers, 
    # and special characters
    $pwd = $pwd + '-+'
    $pwd_filename = ".secret_ad_safe_mode"
    Save-RandomPassword -Path $Path -Name $pwd_filename -Secret $pwd

    $pwd = ConvertTo-SecureString $pwd -AsPlainText -Force 

    # Set these values to your environment
    $ADArguments = @{
        CreateDNSDelegation           = $false
        DatabasePath                  = "C:\Windows\NTDS"
        DomainName                    = $DomainName
        SafeModeAdministratorPassword = $pwd
        DomainNetbiosName             = $NetbiosName
        InstallDns                    = $true
        LogPath                       = "C:\Windows\NTDS"
        NoRebootOnCompletion          = $false
        SysvolPath                    = "C:\Windows\SYSVOL"
        Force                         = $true
    }

    Install-ADDSForest @ADArguments
}


<#
.SYNOPSIS 
    Internal function to install Apache Ant. 
.DESCRIPTION
    Internal function to install Apache Ant. The Apache Ant version to 
    be installed is defined at the top of this script.
.PARAMETER Path
    Root path of the installation, defaults to "C:\".
.EXAMPLE
    Install-ApacheAnt -Path "D:\"
#>
function Install-ApacheAnt {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    # Install Apache Ant 1.10.x
    Write-Host "Installing Apache Ant...`n"
    $pkg = Get-PackageName -Name "apache-ant" -Pkgs $Packages
    if ($Packages[$pkg]['verified']) {
        $apache_ant = [string]$pkg.Split("-bin.zip")
        $apache_ant = $apache_ant.Trim()
        $dl_path = $Path + $Directories["downloads"]
        $installer = $dl_path + $pkg
        $install_path = $Path + $Directories["bin"]
        $ant_bin_path = $install_path + "$apache_ant\bin"
        # Launch installer
        Expand-Archive -Path $installer $install_path | Out-Null

        # Set session environment variables
        $env:ANT_HOME = "$install_path\$apache_ant"
        $env:PATH = "$env:PATH;$ant_bin_path"

        # Install Ant Contrib
        # Extract and copy file to $env:ANT_HOME\lib: ant-contrib-1.0b3.jar
        $ant_contrib = Get-PackageName -Name "ant-contrib" -Pkgs $Packages
        if ($Packages[$ant_contrib]['verified']) {
            Write-Host "Copy Ant Contrib jar to Apache Ant lib directory."
            $ant_contrib_path = $Path + $Directories['downloads'] + $ant_contrib
            $ant_lib_path = "$env:ANT_HOME\lib"
            Add-Type -Assembly System.IO.Compression.FileSystem
            $zip_file = [IO.Compression.ZipFile]::OpenRead($ant_contrib_path)
            $zip_file.Entries | Where-Object ({$_.Name -like 'ant-contrib-1.0b3.jar'}) | foreach {
                                                $FileName = $_.Name 
                                                [System.IO.Compression.ZipFileExtensions]::ExtractToFile($_, 
                                                "$ant_lib_path\$FileName", $true)} 
            $zip_file.Dispose()
            Write-Host "Ant Contrib file copy completed."
        } else {
            Write-Host "Ant Contrib not copied, package failed verification."
        }

        Write-Host "Apache Ant installation completed.`n"
    } else {
        Write-Host "Apache Ant not installed, package failed verification."
    }
}


<#
.SYNOPSIS 
    Internal function to install Apache Tomcat. 
.DESCRIPTION
    Internal function to install Apache Tomcat. The Apache Tomcat version to 
    be installed is defined at the top of this script.
.PARAMETER Path
    Root path of the installation, defaults to "C:\".
.EXAMPLE
    Install-ApacheTomcat -Path "D:\"
#>
function Install-ApacheTomcat {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    # Install Apache Tomcat 9.0.x
    Write-Host "Installing Apache Tomcat...`n"
    $pkg = Get-PackageName -Name "apache-tomcat" -Pkgs $Packages
    $server_name = hostname
    $server_name = $server_name.ToLower()
    if ($Packages[$pkg]['verified']) {
        $apache_tomcat = [string]$pkg.Split(".exe")
        $apache_tomcat = $apache_tomcat.Trim()
        $cat_home = $Path + $Directories["bin"] + $apache_tomcat
        $cat_bin = $cat_home + "\bin"
        $cat_base = $Path + $Directories["tomcat"] + "\$server_name-a"

        $installer = $Path + $Directories["downloads"] + $pkg

        # Launch installer
        .$installer /S /D=$cat_home | Out-Null

        # Install Tomcat Native
        # Extract and copy files to $cat_bin: tcnative-2.dll, openssl.exe
        $t_native = Get-PackageName -Name "tomcat-native" -Pkgs $Packages
        if ($Packages[$t_native]['verified']) {
            Write-Host "Copy Tomcat Native files to Apache Tomcat bin directory."
            $tn_path = $Path + $Directories["downloads"] + $t_native
            Add-Type -Assembly System.IO.Compression.FileSystem
            $zip_file = [IO.Compression.ZipFile]::OpenRead($tn_path)
            [System.IO.Compression.ZipFileExtensions]::ExtractToFile($zip_file.Entries[1], "$cat_bin\openssl.exe", $true)
            [System.IO.Compression.ZipFileExtensions]::ExtractToFile($zip_file.Entries[4], "$cat_bin\tcnative-2.dll", $true)
            $zip_file.Dispose()
            Write-Host "Tomcat Native file copy completed."
        } else {
            Write-Host "Tomcat Native not copied, package failed verification."
        }

        # Set session environment variables
        $env:CATALINA_HOME = $cat_home
        $env:PATH = "$env:PATH;$cat_bin"
        $env:CATALINA_BASE = $cat_base
        Write-Host "Apache Tomcat installation completed.`n"
    } else {
        Write-Host "Apache Tomcat not installed, package failed verification."
    }
}


<#
.SYNOPSIS 
    Internal function to install OpenJDK.
.DESCRIPTION
    Install OpenJDK 21.x.
.PARAMETER Path
    The root path of the application installation.
.EXAMPLE
    Install-OpenSSH
#>
function Install-OpenJDK {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    # Install OpenJDK 21.x
    Write-Host "Installing OpenJDK...`n"
    $pkg = Get-PackageName -Name "openjdk" -Pkgs $Packages
    if ($Packages[$pkg]['verified']) {
        $dl_path = $Path + $Directories["downloads"]
        $installer = $dl_path + $pkg
        $install_path = $Path + $Directories["bin"]
        $jdk_bin_path = $install_path + "jdk-21\bin"
        # Launch installer
        Expand-Archive -Path $installer $install_path | Out-Null

        # Set session environment variables
        $env:JAVA_HOME = $install_path + "jdk-21"
        $env:PATH = "$jdk_bin_path;$env:PATH"

        Write-Host "OpenJDK installation completed.`n"
    } else {
        Write-Host "OpenJDK not installed, package failed verification."
    }
}


<#
.SYNOPSIS 
    Internal function to install the Windows OpenSSH capability.
.DESCRIPTION
    Install the Windows OpenSSH capability.
.EXAMPLE
    Install-OpenSSH
#>
function Install-OpenSSH {
    Write-Host "Installing and starting OpenSSH..."

    # Install OpenSSH (Windows Server 2022)
    Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

    # Starting OpenSSH
    Start-Service sshd

    Write-Host "OpenSSH installed and started."
}


function Install-PostgreSQL {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    # Install PostgreSQL 15.x
    Write-Host "Installing PostgreSQL...`n"
    $pkg = Get-PackageName -Name "postgresql-15.10" -Pkgs $Packages
    if ($Packages[$pkg]['verified']) {
        $installer = $Path + $Directories["downloads"] + $pkg
        $bin_path = $Path + $Directories["bin"] + "postgresql\15"
        $data_path = $Path + $Directories["apps"] + "postgresql\15\data"

        $r_pwd = New-RandomPassword
        $pwd_filename = ".secret_psql"
        Save-RandomPassword -Path $Path -Name $pwd_filename -Secret $r_pwd

        # Launch installer
        .$installer --mode unattended --prefix $bin_path --datadir $data_path --enable_acledit 1 --superpassword $r_pwd | Out-Null

        # Set session environment variables
        $env:PSQL_HOME = $bin_path
        $env:PATH = "$env:PATH;$bin_path"

        # Set firwall rule
        New-NetFirewallRule -Name "PostgreSQL Allow" -Enabled True `
        -DisplayName "PostgreSQL TCP 5432 Inbound Allow" -Direction Inbound `
        -Protocol TCP -LocalPort 5432 -RemoteAddress LocalSubnet -Action Allow `
        -Description "PostgreSQL TCP 5432 Inbound Allow" | Out-Null

        Write-Host "PostgreSQL installation completed.`n"
    } else {
        Write-Host "PostgreSQL not installed, package failed verification."
    }
}


function Install-PowerShell {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    # Install PowerShell 7.5.x
    Write-Host "Installing PowerShell...`n"
    $pkg = Get-PackageName -Name "PowerShell" -Pkgs $BasePackages
    if ($BasePackages[$pkg]['verified']) {
        $pkg_path = $Path + $Directories["downloads"] + $pkg
        $args = "/package $pkg_path /passive ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1 ADD_PATH=1 DISABLE_TELEMETRY=1"

        # Launch installer
        Start-Process msiexec.exe -ArgumentList $args -Wait

        Write-Host "PowerShell installation completed.`n"
    } else {
        Write-Host "PowerShell not installed, package failed verification."
    }
}


function Install-VSCode {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    # Install Visual Studio Code 1.98.x
    # VSCODE_HOME = 'C:\Program Files\Microsoft VS Code'
    $vscode_bin = "C:\Program Files\Microsoft VS Code\bin\code"
    if (-Not (Test-Path -Path $vscode_bin)) {
        Write-Host "Installing Visual Studio Code...`n"
        $pkg = Get-PackageName -Name "VSCodeSetup" -Pkgs $BasePackages          
        if ($BasePackages[$pkg]['verified']) {
            $installer = $Path + $Directories["downloads"] + $pkg

            # Launch installer
            .$installer /VERYSILENT /MERGETASKS=!runcode

            Write-Host "Visual Studio Code installation completed.`n"
        } else {
            Write-Host "Visual Studio Code not installed, package failed verification."
        }
    } else {
        Write-Host "Visual Studio Code already installed, not updating."
    }
}


<#
.SYNOPSIS 
    Internal function to download a specific file.
.DESCRIPTION
    Download the file in the Uri to the file specified in FileName.
.PARAMETER FileName
    The name of the file to be saved. 
.PARAMETER Uri
    The uniform resource indicator of the file to be downloaded.
.EXAMPLE
    Invoke-Downloadd -FileName "test.zip" -Uri "https://test.com/downloads/test.zip"
#>
function Invoke-Download {
    param (
        [Parameter(Mandatory)]
        [string]$FileName,
        [Parameter(Mandatory)]
        [string]$Uri
    )
    Write-Host "Downloading $FileName..."
    $res = Invoke-WebRequest -UseBasicParsing -Uri $Uri -OutFile $FileName -PassThru

    return $res
}


<#
.SYNOPSIS 
    Internal function to create a new AD security group.
.DESCRIPTION
    Internal function to create a new AD security group, by default 
    it creates the Logon As a Service security group. The security 
    group is created in the Groups OU. Defaults to creating the 
    LogonAsService security group.
.PARAMETER Path
    The root installation path. 
.PARAMETER GroupName
    Name of the security group to create.
.PARAMETER Description
    The purpose of the security group. 
.EXAMPLE
    New-ADSecurityGroup -GroupName $GroupName -Description $Description
    New-ADSecurityGroup -GroupName "LogonAsService" -Description "Logon as a service security group"
#>
function New-ADSecurityGroup {
    param (
        [string]$GroupName,
        [string]$Description
    )
    $sec_grp_ou = "OU=" + $ADDomain["GroupOU"] + "," + $ADDomain["RootDN"]
    $display_name = $GroupName
    $GrpParams = @{
        Description = $Description
        DisplayName = $display_name
        GroupCategory = "Security"
        GroupScope = "Global"
        Name = $GroupName
        Path = $sec_grp_ou
        SamAccountName = $GroupName
    }

    Write-Host "Creating new security group $GroupName..."
    New-ADGroup @GrpParams | Out-Null
    if ($?) {
        Write-Host "Security group $GroupName created."
    } else {
        Write-Host "Failed to create security group $GroupName."
    } 
}


<#
.SYNOPSIS 
    Internal function to create a new AD service account.
.DESCRIPTION
    Internal function to create a new AD service account. 
.PARAMETER AccountName
    The SamAccountName of the service account to create.
.PARAMETER AccountPassword
    The `SecureString` password of the service account to create.
.PARAMETER Description
    The purpose of the service account. 
.EXAMPLE
    New-ADServiceAccount -AccountName $AccountName -AccountPassword $AccountPassword -Description $Description
    New-ADServiceAccount -AccountName "svc-httpd" -AccountPassword $AccountPassword -Description "Apache HTTPD service account$?"
#>
function New-ADServiceAccount {
    param (
        [Parameter(Mandatory)]
        [string]$AccountName,
        [Parameter(Mandatory)]
        $AccountPassword,
        [Parameter(Mandatory)]
        [string]$Description
    )
    Import-Module ActiveDirectory
    $sa_ou = "OU=" + $ADDomain["ServiceOU"] + "," + $ADDomain["RootDN"]

    $SvcParams = @{
        AccountPassword = $AccountPassword
        AllowReversiblePasswordEncryption = $false
        CannotChangePassword = $true
        Description = $Description
        Enabled = $true
        Name = $AccountName
        PasswordNeverExpires = $true
        Path = $sa_ou
        SamAccountName = $AccountName
    }
    Write-Host "Adding new service account...$AccountName"
    New-ADUser @SvcParams | Out-Null
    if ($?) {
        Write-Host "New service account...$AccountName, created in $sa_ou."
    } else {
        Write-Host "Failed to create service account - $AccountName in $sa_ou."
    }
}


<#
.SYNOPSIS 
    Internal function to generate a new random password.
.DESCRIPTION
    Internal function to generate a new random password. This random password 
    generator does not support special characters.
.PARAMETER PwLength
    The lenth of password to genrate, defaults to 14.
.EXAMPLE
    New-RandomPassword -PwLength 20
#>
function New-RandomPassword {
    param (
        [int]$PwLength = 14
    )
    # Char 97 - 122 'a-z'
    # Char 65 - 90 'A-Z'
    # Char 48 - 57 '0-9'
    # Char 45 '-'
    # Char 43 '+'
    #skip the letter l
    $alpha_list = [char]97..[char]109 + [char]111..[char]122 + [char]65..[char]90
    $char_list = $alpha_list + [char]48..[char]57 + [char]43 + [char]45

    # Always start password with alpha character
    $pass = [char](Get-Random -InputObject $alpha_list)
    $pass += -Join ((Get-Random -InputObject $char_list -Count ($PwLength - 1)) | ForEach-Object {[char]$_})
    
    return $pass
}


<#
.SYNOPSIS 
    Internal function to save a generated random password to file.
.DESCRIPTION
    Internal function to save a generated random password to file.
.PARAMETER Path
    The root path of apps\secrets.
.PARAMETER Name
    The name of the file to save the gnerated randome password. The password 
    file will be saved to the apps\secrets directory.
.PARAMETER Secret
    The random generated password to be saved to the file.
.EXAMPLE
    Save-RandomPassword -Path "\" -Name ".secret_psql" -Secret $Secret
    Save-RandomPassword -Path "\" -Name ".secret_ad_safe_mode" -Secret $Secret
#>
function Save-RandomPassword {
    param (
        [Parameter(Mandatory)]
        [string]$Path,
        [Parameter(Mandatory)]
        [string]$Name,
        [Parameter(Mandatory)]
        [string]$Secret
    )

    $secrets_path = $Path + $Directories["secrets"] + $Name

    Out-File -FilePath $secrets_path -InputObject $Secret 
}


function Set-ApacheFSPermissions {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    Write-Host "Setting Apache Tomcat directories ownership..."
    $owner =  $ADDomain["TomcatUser"]
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule($owner, 
    "FullControl", "ContainerInherit,ObjectInherit", "InheritOnly", "Allow")

    $tc_pkg_name = Get-PackageName -Name "apache-tomcat" -Pkgs $Packages
    $tc_pkg_name = $tc_pkg_name.Split(".exe")
    $tc_pkg_name = $tc_pkg_name.Trim()

    $tc_bin_path = $Path + $Directories["bin"] + $tc_pkg_name
    $tc_inst_path = $Path + $Directories["tomcat"]
    
    $acl = Get-Acl -Path $tc_bin_path
    $acl.SetOwner([System.Security.Principal.NTAccount]$owner)
    $acl.AddAccessRule($rule)
    Set-Acl -Path $tc_bin_path -AclObject $acl

    $acl = Get-Acl -Path $tc_inst_path
    $acl.SetOwner([System.Security.Principal.NTAccount]$owner)
    $acl.AddAccessRule($rule)
    Set-Acl -Path $tc_inst_path -AclObject $acl
    Write-Host "Completed setting ownership of Apache Tomcat directories."
}


function Set-PermanentEnvVariables {
    param (
        [Parameter(Mandatory)]
        [string]$Path
    )
    Write-Host "Setting permanent environment variables..."
    $bin_path = $Path + $Directories["bin"]
    
    # Set Apache Ant permanent environment variables
    $ant_bin_path = "$env:ANT_HOME\bin"
    [Environment]::SetEnvironmentVariable("ANT_HOME", $env:ANT_HOME, "Machine")
    [Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$ant_bin_path", "Machine")

    # Set Apache Tomcat permanent environment variables
    $cat_bin_path = "$env:CATALINA_HOME\bin"
    [Environment]::SetEnvironmentVariable("CATALINA_HOME", $env:CATALINA_HOME, "Machine")
    [Environment]::SetEnvironmentVariable("PATH","$env:PATH;$cat_bin_path", "Machine")
    [Environment]::SetEnvironmentVariable("CATALINA_BASE", $env:CATALINA_BASE, "Machine")

    # Set OpenJDK permanent environment variables
    $jdk_bin_path = "$env:JAVA_HOME\bin"
    [Environment]::SetEnvironmentVariable("JAVA_HOME", $env:JAVA_HOME, "Machine")
    [Environment]::SetEnvironmentVariable("PATH", "$jdk_bin_path;$env:PATH", "Machine")

    # Set PostgreSQL permanent environment variables
    $psql_home = $bin_path + "postgresql\15"
    $psql_bin_path = $bin_path + "postgresql\15\bin"
    [Environment]::SetEnvironmentVariable("PSQL_HOME", $psql_home, "Machine")
    [Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$psql_bin_path", "Machine")

    Write-Host "Permanent environment variables set."
}